# Generated by Django 5.1 on 2025-12-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(blank=True, help_text='Path da imagem de perfil no bucket S3 (ex: profiles/user_123/avatar.jpg)', max_length=500, null=True),
        ),
    ]
