# Generated by Django 5.1 on 2025-12-04 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('users', '0002_profile_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPatientRelation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now_add=True, help_text='Data de início do relacionamento')),
                ('end_date', models.DateTimeField(blank=True, help_text='Data de fim do relacionamento (se aplicável)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionais sobre o relacionamento', null=True)),
                ('patient', models.ForeignKey(help_text='Paciente sendo atendido', on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='patients.patient')),
                ('user', models.ForeignKey(help_text='Usuário que atende o paciente', on_delete=django.db.models.deletion.CASCADE, related_name='patient_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relacionamento Usuário-Paciente',
                'verbose_name_plural': 'Relacionamentos Usuário-Paciente',
                'indexes': [models.Index(fields=['user', 'is_active'], name='users_userp_user_id_16bf0c_idx'), models.Index(fields=['patient', 'is_active'], name='users_userp_patient_ffe8d2_idx')],
                'unique_together': {('user', 'patient')},
            },
        ),
    ]
