# Generated by Django 5.1 on 2026-01-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='factory_mode',
            field=models.BooleanField(default=False, help_text='Indica se o usuário pode acessar o modo fábrica'),
        ),
    ]
