# Generated by Django 5.1 on 2026-01-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_factory_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='clickhouse_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='legacy_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID do usuário no sistema legado', null=True),
        ),
    ]
