# Generated by Django 5.1 on 2025-12-04 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('transfer_keys', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=list)),
                ('clickhouse_id', models.UUIDField(unique=True)),
                ('metadata', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'indexes': [models.Index(fields=['is_active'], name='projects_pr_is_acti_f7dee7_idx'), models.Index(fields=['name'], name='projects_pr_name_11d782_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_users', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project user',
                'verbose_name_plural': 'Project users',
                'indexes': [models.Index(fields=['project', 'user'], name='projects_pr_project_6e74a7_idx'), models.Index(fields=['user', 'project'], name='projects_pr_user_id_9b0aa4_idx'), models.Index(fields=['is_active'], name='projects_pr_is_acti_696325_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'project'), name='uq_projectuser_user_project')],
            },
        ),
    ]
