# Generated by Django 5.1 on 2025-12-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_delete_deviceproject'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectUser',
        ),
    ]
