# Generated by Django 5.1 on 2025-12-04 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('serial', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('origin', models.PositiveSmallIntegerField(choices=[(1, 'MedIO'), (2, 'MicroFlow'), (3, 'NexoUWB')], default=1)),
                ('iccid', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('sold', models.BooleanField(blank=True, db_index=True, null=True)),
                ('sold_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lock', models.BooleanField(blank=True, db_index=True, null=True)),
                ('lock_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tested', models.BooleanField(blank=True, db_index=True, null=True)),
                ('tested_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('clickhouse_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='devices_dev_is_acti_52b321_idx'), models.Index(fields=['origin'], name='devices_dev_origin_7cbe36_idx'), models.Index(fields=['serial'], name='devices_dev_serial_31b10e_idx'), models.Index(fields=['iccid'], name='devices_dev_iccid_cc5766_idx'), models.Index(fields=['model_name'], name='devices_dev_model_n_c55331_idx'), models.Index(fields=['sold', 'sold_at'], name='devices_dev_sold_fad68e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(db_index=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='devices.device')),
            ],
            options={
                'ordering': ['device', '-read_at'],
                'indexes': [models.Index(fields=['device', '-read_at'], name='idx_devloc_dev_readat_desc')],
                'constraints': [models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='latitude_range'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='longitude_range')],
            },
        ),
        migrations.CreateModel(
            name='DeviceNfeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nfe', models.CharField(max_length=255)),
                ('nfe_date', models.DateTimeField()),
                ('cfop', models.PositiveIntegerField(blank=True, null=True)),
                ('ciof', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(default='Tecnicon', max_length=64)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfe_history', to='devices.device')),
            ],
            options={
                'verbose_name': 'Device NFe history',
                'verbose_name_plural': 'Device NFe histories',
                'ordering': ['device', '-nfe_date'],
                'indexes': [models.Index(fields=['device', 'nfe_date'], name='devices_dev_device__10e096_idx'), models.Index(fields=['device', '-nfe_date'], name='idx_dev_nfe_desc'), models.Index(fields=['nfe'], name='devices_dev_nfe_937ac9_idx'), models.Index(fields=['is_active'], name='devices_dev_is_acti_312674_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_projects', to='devices.device')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_projects', to='projects.project')),
            ],
            options={
                'verbose_name': 'Device project',
                'verbose_name_plural': 'Device projects',
                'indexes': [models.Index(fields=['project', 'device'], name='devices_dev_project_c914cb_idx'), models.Index(fields=['device', 'project'], name='devices_dev_device__a2055c_idx'), models.Index(fields=['is_active'], name='devices_dev_is_acti_9f644b_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'project'), name='uq_deviceproject_device_project')],
            },
        ),
    ]
