# Generated by Django 5.1 on 2026-01-14 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('sold', 'Sold'), ('sent', 'Sent'), ('tested', 'Tested'), ('locked', 'Locked'), ('unlocked', 'Unlocked')], db_index=True, help_text='Tipo de evento: sold, sent, tested, locked, unlocked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data e hora da ocorrência do evento')),
            ],
            options={
                'verbose_name': 'Device Event',
                'verbose_name_plural': 'Device Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceTelemetryModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linked_at', models.DateTimeField(blank=True, help_text='Data de vinculação do módulo ao device', null=True)),
                ('unlinked_at', models.DateTimeField(blank=True, help_text='Data de desvinculação (se aplicável)', null=True)),
                ('is_linked', models.BooleanField(default=True, help_text='Se o vínculo está ativo')),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryModule',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(db_index=True, help_text='Identificador único do módulo de telemetria', max_length=16, unique=True)),
                ('icc_id', models.CharField(db_index=True, help_text='Identificador ICC do chip SIM', max_length=20)),
                ('modelo', models.CharField(db_index=True, help_text='Modelo do módulo GPS/telemetria', max_length=12)),
                ('last_online_at', models.DateTimeField(blank=True, db_index=True, help_text='Última vez que o módulo esteve online', null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='devices_dev_origin_7cbe36_idx',
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='devices_dev_iccid_cc5766_idx',
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='devices_dev_model_n_c55331_idx',
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='devices_dev_sold_fad68e_idx',
        ),
        migrations.RemoveField(
            model_name='device',
            name='clickhouse_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='iccid',
        ),
        migrations.RemoveField(
            model_name='device',
            name='lock',
        ),
        migrations.RemoveField(
            model_name='device',
            name='lock_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='device',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='device',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='sold_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='tested_at',
        ),
        migrations.AddField(
            model_name='device',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(db_index=True, default='undefined', max_length=24),
        ),
        migrations.AddField(
            model_name='device',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial',
            field=models.CharField(db_index=True, default='', max_length=22),
        ),
        migrations.AlterField(
            model_name='device',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='tested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Device que possui esta localização', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='devices.device'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['model'], name='devices_dev_model_3ec8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['sold'], name='devices_dev_sold_dd7480_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['locked'], name='devices_dev_locked_370a05_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['tested'], name='devices_dev_tested_b65799_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['sent'], name='devices_dev_sent_272d66_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['created'], name='devices_dev_created_c31d23_idx'),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='device',
            field=models.ForeignKey(help_text='Device relacionado ao evento', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='devices.device'),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='user',
            field=models.ForeignKey(help_text='Usuário que criou o evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicetelemetrymodule',
            name='device',
            field=models.ForeignKey(help_text='Device vinculado ao módulo', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_links', to='devices.device'),
        ),
        migrations.AddIndex(
            model_name='telemetrymodule',
            index=models.Index(fields=['imei'], name='devices_tel_imei_3dd006_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrymodule',
            index=models.Index(fields=['icc_id'], name='devices_tel_icc_id_26adce_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrymodule',
            index=models.Index(fields=['modelo'], name='devices_tel_modelo_91be5d_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrymodule',
            index=models.Index(fields=['is_active'], name='devices_tel_is_acti_d4e6a7_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrymodule',
            index=models.Index(fields=['last_online_at'], name='devices_tel_last_on_855b69_idx'),
        ),
        migrations.AddConstraint(
            model_name='telemetrymodule',
            constraint=models.UniqueConstraint(fields=('imei',), name='unique_telemetry_module_imei'),
        ),
        migrations.AddField(
            model_name='devicetelemetrymodule',
            name='module',
            field=models.ForeignKey(help_text='Módulo de telemetria vinculado', on_delete=django.db.models.deletion.CASCADE, related_name='device_telemetry_links', to='devices.telemetrymodule'),
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Módulo de telemetria que enviou esta localização', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='devices.telemetrymodule'),
        ),
        migrations.AddIndex(
            model_name='devicelocation',
            index=models.Index(fields=['module', '-read_at'], name='devices_dev_module__c1c997_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['device', '-created_at'], name='devices_dev_device__eaa371_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['event', '-created_at'], name='devices_dev_event_1b2954_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['device', 'event', '-created_at'], name='devices_dev_device__5eac94_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetelemetrymodule',
            index=models.Index(fields=['device', 'module'], name='devices_dev_device__feee41_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetelemetrymodule',
            index=models.Index(fields=['module', 'device'], name='devices_dev_module__e0559d_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetelemetrymodule',
            index=models.Index(fields=['is_linked'], name='devices_dev_is_link_deca48_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetelemetrymodule',
            index=models.Index(fields=['linked_at'], name='devices_dev_linked__7d5ea0_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicetelemetrymodule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_linked', True)), fields=('device', 'module'), name='unique_active_device_telemetry_module'),
        ),
    ]
