# Generated by Django 5.1 on 2026-01-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_deviceevent_devicetelemetrymodule_telemetrymodule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelocation',
            name='accuracy',
            field=models.IntegerField(blank=True, help_text='Precisão da localização em metros', null=True),
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='altitude',
            field=models.IntegerField(blank=True, help_text='Altitude em metros', null=True),
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='battery',
            field=models.IntegerField(blank=True, help_text='Nível de bateria em porcentagem (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='course',
            field=models.IntegerField(blank=True, help_text='Direção do movimento em graus (0-360)', null=True),
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='is_moving',
            field=models.BooleanField(blank=True, help_text='Indica se o device está em movimento', null=True),
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='signal_strength',
            field=models.IntegerField(blank=True, help_text='Força do sinal (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='speed',
            field=models.FloatField(blank=True, help_text='Velocidade em km/h', null=True),
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
