# Generated by Django 5.1 on 2026-01-22 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_devicelocation_accuracy_devicelocation_altitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFeatures',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título do recurso (ex: Manual do Usuário)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrição do recurso', null=True)),
                ('file_url', models.CharField(blank=True, help_text='Path do arquivo no bucket S3 (ex: device-features/feature_id/manual.pdf)', max_length=500, null=True)),
                ('kind', models.CharField(db_index=True, help_text='Tipo do recurso (ex: manual, datasheet, firmware, video)', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Nome do ícone ou URL', max_length=100, null=True)),
                ('order', models.IntegerField(db_index=True, default=0, help_text='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Device Feature',
                'verbose_name_plural': 'Device Features',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLease',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lease_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador único do contrato de aluguel', unique=True)),
                ('start_date', models.DateTimeField(db_index=True, help_text='Data de início do aluguel')),
                ('end_date', models.DateTimeField(blank=True, db_index=True, help_text='Data de término do aluguel', null=True)),
                ('rating_delivery', models.IntegerField(blank=True, help_text='Avaliação da entrega (1-5)', null=True)),
                ('rating_buy', models.IntegerField(blank=True, help_text='Avaliação da compra (1-5)', null=True)),
            ],
            options={
                'verbose_name': 'Device Lease',
                'verbose_name_plural': 'Device Leases',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome do modelo (ex: Medidor de Glicose XYZ)', max_length=200)),
                ('slug', models.SlugField(help_text='Slug único para URLs (gerado automaticamente do nome)', max_length=200, unique=True)),
                ('icon_url', models.CharField(blank=True, help_text='Path do ícone no bucket S3 (ex: device-models/slug/icon.png)', max_length=500, null=True)),
                ('description', models.TextField(blank=True, help_text='Descrição do modelo', null=True)),
            ],
            options={
                'verbose_name': 'Device Model',
                'verbose_name_plural': 'Device Models',
            },
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='devices_dev_model_3ec8a0_idx',
        ),
        migrations.RemoveField(
            model_name='device',
            name='model',
        ),
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição do dispositivo', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, help_text='Nome customizado do dispositivo', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='rating_buy',
            field=models.IntegerField(blank=True, help_text='Avaliação da compra (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='rating_delivery',
            field=models.IntegerField(blank=True, help_text='Avaliação da entrega (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='secret',
            field=models.CharField(blank=True, help_text='Chave secreta do dispositivo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='token',
            field=models.UUIDField(blank=True, db_index=True, help_text='Token de autenticação do dispositivo', null=True),
        ),
        migrations.AddField(
            model_name='devicelease',
            name='device',
            field=models.ForeignKey(help_text='Dispositivo alugado', on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='devices.device'),
        ),
        migrations.AddField(
            model_name='devicelease',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuário que alugou o dispositivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='lease',
            field=models.ForeignKey(blank=True, help_text='Contrato de aluguel ativo (se houver)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_devices', to='devices.devicelease'),
        ),
        migrations.AddIndex(
            model_name='devicemodel',
            index=models.Index(fields=['slug'], name='devices_dev_slug_a908e5_idx'),
        ),
        migrations.AddIndex(
            model_name='devicemodel',
            index=models.Index(fields=['is_active'], name='devices_dev_is_acti_2467cf_idx'),
        ),
        migrations.AddField(
            model_name='devicefeatures',
            name='device_model',
            field=models.ForeignKey(help_text='Modelo de dispositivo ao qual este recurso pertence', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='devices.devicemodel'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.ForeignKey(blank=True, help_text='Modelo do dispositivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.devicemodel'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_model'], name='devices_dev_device__629817_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['token'], name='devices_dev_token_499d32_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['lease'], name='devices_dev_lease_i_b0a8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelease',
            index=models.Index(fields=['device', '-start_date'], name='devices_dev_device__c85a86_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelease',
            index=models.Index(fields=['lease_id'], name='devices_dev_lease_i_ccd14b_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelease',
            index=models.Index(fields=['user', '-start_date'], name='devices_dev_user_id_85c413_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelease',
            index=models.Index(fields=['is_active'], name='devices_dev_is_acti_16d255_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefeatures',
            index=models.Index(fields=['device_model', 'order'], name='devices_dev_device__219320_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefeatures',
            index=models.Index(fields=['kind'], name='devices_dev_kind_4bfee2_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefeatures',
            index=models.Index(fields=['is_active'], name='devices_dev_is_acti_0d7469_idx'),
        ),
    ]
