"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from dotenv import load_dotenv
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

SECRET_KEY = os.getenv("SECRET_KEY", "unsafe-default-key")
DEBUG = os.getenv("DEBUG", "False") == "True"
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "loggin",
    "users.apps.UsersConfig",
    "devices",
    "projects",
    'drf_spectacular',
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
    'DEFAULT_PARSER_CLASSES': ['rest_framework.parsers.JSONParser'],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # para web
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # para app
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

}

SPECTACULAR_SETTINGS = {
    "TITLE": "Medical San Loggin API",
    "DESCRIPTION": "API Web e Mobile do sistema Loggin com endpoints organizados por plataforma",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/",
    "CONTACT": {
        "name": "Medical San Support",
        "email": "support@medicalsan.com",
    },
    "LICENSE": {
        "name": "Private License",
    },
    "SERVERS": [
        {
            "url": "http://localhost:8000",
            "description": "Development Server",
        },
        {
            "url": "http://3.236.36.55:8000",
            "description": "Production Server (AWS)",
        },
    ],
    "TAGS": [
        {
            "name": "Web - Auth",
            "description": "Endpoints de autenticação para aplicação web (login, registro, recuperação de senha)",
        },
        {
            "name": "Web - User",
            "description": "Endpoints de gerenciamento de usuários para aplicação web",
        },
        {
            "name": "Mobile - Auth",
            "description": "Endpoints de autenticação para aplicação mobile (login, registro, recuperação de senha)",
        },
        {
            "name": "Mobile - User",
            "description": "Endpoints de gerenciamento de usuários para aplicação mobile",
        },
        {
            "name": "User Management",
            "description": "Endpoints gerais para gerenciamento de perfis e upload de imagens",
        },
    ],
    "SECURITY_SCHEMES": {
        "bearerAuth": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
        },
        # Se quiser documentar autenticação por cookie/sessão
        # "cookieAuth": {
        #     "type": "apiKey",
        #     "in": "cookie",
        #     "name": "sessionid",
        # },
    },
    "SECURITY": [
        {"bearerAuth": []},
        # {"cookieAuth": []},
    ],
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "app.urls"
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "loggin" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {"context_processors": [
            "django.template.context_processors.debug",
            "django.template.context_processors.request",
            "django.contrib.auth.context_processors.auth",
            "django.contrib.messages.context_processors.messages",
        ]},
    },
]
WSGI_APPLICATION = "app.wsgi.application"

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', os.path.join(BASE_DIR, 'db.sqlite3')),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
    }
}

STATIC_URL = "static/"

# URL para redirecionamento quando login é necessário
LOGIN_URL = '/login/'

if DEBUG:
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# Permitir origens específicas em desenvolvimento e produção
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://100.68.165.52:8000",
    "http://3.236.36.55:8000",  # Produção AWS
    os.getenv('FRONTEND_URL', 'http://localhost:8000'),  # URL dinâmica do .env
]

# Configurações de Email
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Para desenvolvimento - emails no console
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'   # Para produção - SMTP real

# Configurações SMTP (para quando usar o backend SMTP real)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@medicalsan.com')

# URL do frontend para links de recuperação
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:8000')

# ============================
# AWS S3 Configuration for File Uploads
# ============================
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', 'medicalsan-uploads')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'

# Configurações de upload de imagens de perfil
PROFILE_IMAGE_MAX_SIZE = (800, 800)  # pixels (largura, altura)
PROFILE_IMAGE_QUALITY = 85  # qualidade JPEG (0-100)
PROFILE_IMAGE_MAX_FILE_SIZE = 5 * 1024 * 1024  # 5MB em bytes

# Configurações opcionais do S3
AWS_S3_FILE_OVERWRITE = False  # Não sobrescrever arquivos com mesmo nome
AWS_DEFAULT_ACL = 'public-read'  # Imagens de perfil são públicas por padrão