# Generated by Django 5.1 on 2025-12-10 17:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome do grupo de clínicas', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descrição opcional do grupo')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'indexes': [models.Index(fields=['name'], name='groups_grou_name_0806de_idx'), models.Index(fields=['is_active'], name='groups_grou_is_acti_044fa7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome da clínica', max_length=255)),
                ('address', models.TextField(blank=True, help_text='Endereço da clínica')),
                ('phone', models.CharField(blank=True, help_text='Telefone da clínica', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email da clínica', max_length=254)),
                ('group', models.ForeignKey(help_text='Grupo ao qual a clínica pertence', on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='groups.group')),
            ],
            options={
                'verbose_name': 'Clinic',
                'verbose_name_plural': 'Clinics',
            },
        ),
        migrations.CreateModel(
            name='GroupAdmin',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permissions', models.JSONField(blank=True, default=list, help_text='Permissões específicas do admin neste grupo')),
                ('group', models.ForeignKey(help_text='Grupo administrado pelo usuário', on_delete=django.db.models.deletion.CASCADE, related_name='group_admins', to='groups.group')),
                ('user', models.ForeignKey(help_text='Usuário administrador do grupo', on_delete=django.db.models.deletion.CASCADE, related_name='group_admins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Admin',
                'verbose_name_plural': 'Group Admins',
            },
        ),
        migrations.CreateModel(
            name='DeviceClinic',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='Data de atribuição do device à clínica')),
                ('notes', models.TextField(blank=True, help_text='Notas sobre a instalação/atribuição')),
                ('clinic', models.ForeignKey(help_text='Clínica onde o device está instalado', on_delete=django.db.models.deletion.CASCADE, related_name='clinic_devices', to='groups.clinic')),
                ('device', models.ForeignKey(help_text='Device associado à clínica', on_delete=django.db.models.deletion.CASCADE, related_name='device_clinics', to='devices.device')),
            ],
            options={
                'verbose_name': 'Device Clinic',
                'verbose_name_plural': 'Device Clinics',
                'indexes': [models.Index(fields=['device', 'clinic'], name='groups_devi_device__2ac88e_idx'), models.Index(fields=['clinic', 'device'], name='groups_devi_clinic__157f40_idx'), models.Index(fields=['assigned_at'], name='groups_devi_assigne_96d6e9_idx'), models.Index(fields=['is_active'], name='groups_devi_is_acti_ae0c12_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('device', 'clinic'), name='unique_active_device_clinic')],
            },
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['name'], name='groups_clin_name_25b898_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['group'], name='groups_clin_group_i_0813a5_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['is_active'], name='groups_clin_is_acti_cea2b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinic',
            constraint=models.UniqueConstraint(fields=('name', 'group'), name='unique_clinic_name_per_group'),
        ),
        migrations.AddIndex(
            model_name='groupadmin',
            index=models.Index(fields=['user', 'group'], name='groups_grou_user_id_33c915_idx'),
        ),
        migrations.AddIndex(
            model_name='groupadmin',
            index=models.Index(fields=['group', 'user'], name='groups_grou_group_i_f4423b_idx'),
        ),
        migrations.AddIndex(
            model_name='groupadmin',
            index=models.Index(fields=['is_active'], name='groups_grou_is_acti_228606_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupadmin',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='unique_user_group_admin'),
        ),
    ]
