# Generated by Django 5.1 on 2025-12-10 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClinic',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, help_text='Função do usuário na clínica (médico, enfermeiro, etc.)', max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True, help_text='Data de início do vínculo')),
                ('end_date', models.DateTimeField(blank=True, help_text='Data de fim do vínculo (se aplicável)', null=True)),
                ('clinic', models.ForeignKey(help_text='Clínica onde o usuário trabalha', on_delete=django.db.models.deletion.CASCADE, related_name='clinic_users', to='groups.clinic')),
                ('user', models.ForeignKey(help_text='Usuário vinculado à clínica', on_delete=django.db.models.deletion.CASCADE, related_name='user_clinics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Clinic',
                'verbose_name_plural': 'User Clinics',
                'indexes': [models.Index(fields=['user', 'clinic'], name='groups_user_user_id_28bb29_idx'), models.Index(fields=['clinic', 'user'], name='groups_user_clinic__549e81_idx'), models.Index(fields=['is_active'], name='groups_user_is_acti_02da9d_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'clinic'), name='unique_user_clinic')],
            },
        ),
    ]
