# Generated by Django 5.1 on 2026-01-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_add_clinic_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.TextField(blank=True, help_text='Endereço da clínica', null=True),
        ),
    ]
