# Generated by Django 5.1 on 2026-01-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_add_clinic_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='address',
        ),
        migrations.AddField(
            model_name='clinic',
            name='clinic_image',
            field=models.CharField(blank=True, help_text='Path da imagem da clínica no bucket S3 (ex: clinics/clinic_123/image.jpg)', max_length=500, null=True),
        ),
    ]
