# Generated by Django 5.1 on 2025-12-10 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Clínica à qual o paciente pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='groups.clinic'),
        ),
    ]
