# Generated by Django 5.1 on 2025-12-10 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_userclinic'),
        ('patients', '0002_patient_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='clinic',
        ),
        migrations.AddField(
            model_name='patient',
            name='group',
            field=models.ForeignKey(default='8e719a74-81ca-4424-b8f1-566eb5fa8e03', help_text='Grupo ao qual o paciente pertence', on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='groups.group'),
            preserve_default=False,
        ),
    ]
