# Generated by Django 5.1 on 2026-01-22 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_clinic_patient_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='anamnese',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor_name',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='user',
            field=models.ForeignKey(help_text='Doutor que criou o prontuário', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.TextField(help_text='Dados da anamnese em formato de texto/JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('patients', models.ManyToManyField(help_text='Pacientes associados a esta anamnese', related_name='anamneses', to='patients.patient')),
                ('user', models.ForeignKey(help_text='Médico que criou a anamnese', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anamneses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anamnesis',
                'verbose_name_plural': 'Anamneses',
                'ordering': ['-created_at'],
            },
        ),
    ]
